import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar />
        <main className="p-4 ">{children}</main>
        <footer className="flex justify-around items-center bg-gray-200 dark:bg-slate-900 h-12">
          <span>Contact Us: User@gmail.com</span>
          <span>Author: Mateusz Barzenc</span>
          <span>Year of creation: 2024</span>
        </footer>
      </body>
    </html>
  );
}
